### ISSUE TITLE
v4 beta 2 fails to find (dynamic parts of the) default font

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-demos-node#56]
Awesome to see the new beta.

I was trying to update a personal project to the beta 2 but ran into trouble.

In a somewhat complex setup, I got something that looks like the CJS version loading the fonts from the wrong location:

```
Error: Cannot find module '/foo/node_modules/mathjax-full/cjs/output/svg/fonts/svg/dynamic/double-struck'
Require stack:
- /foo/node_modules/mathjax-full/cjs/util/asyncLoad/node.js
- /foo/postprocess.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1060:15)
    at Module._load (node:internal/modules/cjs/loader:905:27)
    at Module.require (node:internal/modules/cjs/loader:1127:19)
    at require (node:internal/modules/helpers:112:18)
    at mathjax_js_1.mathjax.asyncLoad (/foo/node_modules/mathjax-full/cjs/util/asyncLoad/node.js:31:16)
    at /foo/node_modules/mathjax-full/cjs/util/AsyncLoad.js:10:43
    at new Promise (<anonymous>)
    at asyncLoad (/foo/node_modules/mathjax-full/cjs/util/AsyncLoad.js:9:12)
    at MathJaxModernFont.<anonymous> (/foo/node_modules/mathjax-full/cjs/output/common/FontData.js:477:68)
    at step (/foo/node_modules/mathjax-full/cjs/output/common/FontData.js:44:23) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/foo/node_modules/mathjax-full/cjs/util/asyncLoad/node.js',
    '/foo/postprocess.js'
  ]
}
something went wrong at  \mathbb{F} Error: MathJax retry
    at retryAfter (/foo/node_modules/mathjax-full/cjs/util/Retries.js:25:15)
    at exports.FontData.FontData.getChar (/foo/node_modules/mathjax-full/cjs/output/common/FontData.js:579:41)
    at exports.CommonWrapper.CommonWrapper.getVariantChar (/foo/node_modules/mathjax-full/cjs/output/common/Wrapper.js:768:30)
    at CommonTextNodeMixin.CommonTextNodeMixin.computeBBox (/foo/node_modules/mathjax-full/cjs/output/common/Wrappers/TextNode.js:61:42)
    at exports.CommonWrapper.CommonWrapper.getBBox (/foo/node_modules/mathjax-full/cjs/output/common/Wrapper.js:208:14)
    at exports.CommonWrapper.CommonWrapper.getOuterBBox (/foo/node_modules/mathjax-full/cjs/output/common/Wrapper.js:216:25)
    at exports.CommonWrapper.CommonWrapper.computeBBox (/foo/node_modules/mathjax-full/cjs/output/common/Wrapper.js:260:35)
    at CommonMiMixin.CommonMiMixin.computeBBox (/foo/node_modules/mathjax-full/cjs/output/common/Wrappers/mi.js:27:42)
    at exports.CommonWrapper.CommonWrapper.getBBox (/foo/node_modules/mathjax-full/cjs/output/common/Wrapper.js:208:14)
    at exports.CommonWrapper.CommonWrapper.getOuterBBox (/foo/node_modules/mathjax-full/cjs/output/common/Wrapper.js:216:25) {
  retry: Promise { <pending> }
}
```

Here's a minimal example script that crashes for me when hitting the "dynamic" parts of the font (actually not quite minimal - as you'll see I tried setting the font manually).

```
// MathML to SVG / CHTML
const mathjax = require('mathjax-full/cjs/mathjax.js').mathjax;
require('mathjax-full/cjs/util/asyncLoad/node.js');
const MathML = require('mathjax-full/cjs/input/mathml.js').MathML;
const SVG = require('mathjax-full/cjs/output/svg.js').SVG;
const jsdom = require('jsdom');
const { JSDOM } = jsdom;
const jsdomadaptor = require('mathjax-full/cjs/adaptors/jsdomAdaptor.js')
    .jsdomAdaptor;
const RegisterHTMLHandler = require('mathjax-full/cjs/handlers/html.js')
    .RegisterHTMLHandler;
const adaptor = jsdomadaptor(JSDOM);
RegisterHTMLHandler(adaptor);
const mml = new MathML();
const MathJaxModernFont = require('mathjax-modern-font/cjs/svg.js').MathJaxModernFont;
const modernFont = new MathJaxModernFont({
    dynamicPrefix: 'mathjax-modern-font/cjs/svg/dynamic'
});

const svg = new SVG({
    font: modernFont,
    displayOverflow: 'overflow',
    linebreaks: {
        inline: false,
    }
});
const svghtml = mathjax.document('', { InputJax: mml, OutputJax: svg });


const mjx = svghtml.convert(process.argv[2] || `<math><mtext>hello</mtext></math>`);

console.log(mjx.outerHTML)
```

This works with the default input but e.g. `<math><mi mathvariant="double-struck">x</mi></math>` crashes as follows

```
/foo/node_modules/mathjax-full/cjs/core/MathDocument.js:181
            finally { if (e_4) throw e_4.error; }
                               ^

Error: MathJax retry
    at retryAfter (/foo/node_modules/mathjax-full/cjs/util/Retries.js:25:15)
    at exports.FontData.FontData.getChar (/foo/node_modules/mathjax-full/cjs/output/common/FontData.js:579:41)
    at exports.CommonWrapper.CommonWrapper.getVariantChar (/foo/node_modules/mathjax-full/cjs/output/common/Wrapper.js:768:30)
    at CommonTextNodeMixin.CommonTextNodeMixin.computeBBox (/foo/node_modules/mathjax-full/cjs/output/common/Wrappers/TextNode.js:61:42)
    at exports.CommonWrapper.CommonWrapper.getBBox (/foo/node_modules/mathjax-full/cjs/output/common/Wrapper.js:208:14)
    at exports.CommonWrapper.CommonWrapper.getOuterBBox (/foo/node_modules/mathjax-full/cjs/output/common/Wrapper.js:216:25)
    at exports.CommonWrapper.CommonWrapper.computeBBox (/foo/node_modules/mathjax-full/cjs/output/common/Wrapper.js:260:35)
    at CommonMiMixin.CommonMiMixin.computeBBox (/foo/node_modules/mathjax-full/cjs/output/common/Wrappers/mi.js:27:42)
    at exports.CommonWrapper.CommonWrapper.getBBox (/foo/node_modules/mathjax-full/cjs/output/common/Wrapper.js:208:14)
    at exports.CommonWrapper.CommonWrapper.getOuterBBox (/foo/node_modules/mathjax-full/cjs/output/common/Wrapper.js:216:25) {
  retry: Promise { <pending> }
```

**Comment by dpvc** [comment]
There are a couple of things that are underlying your issues.

First, the `font` property in the `svg` configuration block is meant to be a string that indicates the font to load when you are using components.  Since you are loading the modules directly, that never actually gets used, so you are not actually supplying the font object.  In v3, the `font` property was a `FontData` instance or subclass, but that changed in v4; I need to add that to the release notes, but I suspect you are the only one who may have been using it, since there were no other fonts to work with in v3.

Instead, you use the new `fontData` configuration property for `svg` to specify the `FontData` instance or class.

So one option would be to do

``` js
const svg = new SVG({
    fontData: modernFont,
    displayOverflow: 'overflow',
    linebreaks: {
        inline: false,
    }
});
```

But since the default font is mathjax-modern, you could just do

``` js
const svg = new SVG({
    fontData: MathJaxModernFont,
    dynamicPrefix: 'mathjax-modern-font/cjs/svg/dynamic'
    displayOverflow: 'overflow',
    linebreaks: {
        inline: false,
    }
});
```

as the `SVG` constructor will create the `FontData` instance from the default `fontData` class (mathjax-modern) and pass it the needed options (`dynamicPrefix` in this case).  Then you don't need to create `mathjaxFont` at all and can leave out those lines.

If you are planning to use a different font, you could do something like

``` js
const svg = new SVG({
    fontData: MathJaxModernFont,
    dynamicPrefix: 'mathjax-modern-font/cjs/svg/dynamic'
    displayOverflow: 'overflow',
    linebreaks: {
        inline: false,
    }
});
```
 where `MathJaxModernFont` is replaced by the class for whatever font you want to use, and again the `SVG` constructor will instantiate it with the given options.

It may be possible to make the `font` option only available when you are using components, so you would at least get an error message for your original code.  I can probably do better with default `dynamicPrefix` for non-component use cases, as the `SVG` and `CHTML` components set that for the given font themselves and the defaults in the actual modules are not used in that case.  but for now, setting it in the SVG options should do the trick.

The other issue with the `MathJax retry` error is actually the expected result, since the double-struck characters are in a dynamically loaded font file, so when MathJax first encounters the need, it must load that file, and that causes the retry.  You must use promises to handle that; but the `convert()` method doesn't have a promise-based counterpart, so you have to handle that yourself using `mathjax.handleRetriesFor()`, as in

``` js
mathjax.handleRetriesFor(() => {
  const mjx = svghtml.convert(process.argv[2] || `<math><mtext mathvariant="double-struck">hello</mtext></math>`);
  console.log(mjx.outerHTML);
});
```

There are functions that you can use to ask the font to load all the dynamic parts initially before you start doing the conversions, so that you would not need to use `handleRetriesFor()`.  You could do

``` js
modernFont.loadDynamicFilesSync();
```

after creating the `modernFont` instance, or you could do 

``` js
svg.font.loadDynamicFilesSync();
```

after creating the `svg` or `svghtml` objects to allow you to use the `convert()` call synchronously.

In a web-based environment, you would need to use `loadDynamicFiles()`, which returns a promise that resolves when all the dynamic files are loaded, so you would need to wait for that promise before doing the `convert()`, though it is probably better to use `handleRetriesFor()` and not load all the file, as there can be quite a few of them.

Anyway, with those changes, you should be able to get it to work.

**Comment by pkra** [comment]
Thanks so much for your help and clarifications, Davide! Works like a charm - on to more dabbling.
